language: java
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.gradle"
jobs:
  include:
    - stage: build
      if: tag IS blank
      install: skip
      before_script: if [[ $encrypted_d0c8c7a16e6b_key ]]; then openssl aes-256-cbc -K $encrypted_d0c8c7a16e6b_key -iv $encrypted_d0c8c7a16e6b_iv -in secring.gpg.enc -out secring.gpg -d; fi
      script: ./gradlew clean build

    - stage: deploy
      if: tag =~ ^\d+\.\d+\.\d+$
      install: skip
      before_script: openssl aes-256-cbc -K $encrypted_d0c8c7a16e6b_key -iv $encrypted_d0c8c7a16e6b_iv -in secring.gpg.enc -out secring.gpg -d
      script: ./gradlew clean build publishToSonatype closeAndReleaseRepository
env:
  global:
    - signingSecretKeyRingFile="`pwd`/secring.gpg"
    #
    #  secure section for maven central deployment, individual for each project
    #  provides properties:
    #    repositoryUser=
    #    repositoryPassword=
    #    signingKeyId=
    #    signingPassword=
    #  looks like:
    #    - secure: "0gcv..."
    #    - secure: "XKrf..."
    #    - secure: "FDGd..."
    #    - secure: "gDfe..."
    #
