language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.gradle"
jobs:
  include:
    - stage: build
      if: tag IS blank
      install: skip
      before_script: #SCRIPT HERE
      script: ./gradlew clean build

    - stage: deploy
      if: tag =~ ^\d+\.\d+\.\d+$
      install: skip
      before_script: #SCRIPT HERE
      script: ./gradlew -Dorg.gradle.internal.publish.checksums.insecure=true --info clean build publishToSonatype closeAndReleaseRepository
env:
  global:
    - signingSecretKeyRingFile="`pwd`/secring.gpg"
    #
    #  secure section for maven central deployment, individual for each project
    #  provides properties:
    #    repositoryUser=
    #    repositoryPassword=
    #    signingKeyId=
    #    signingPassword=
    #  looks like:
    #    - secure: "0gcv..."
    #    - secure: "XKrf..."
    #    - secure: "FDGd..."
    #    - secure: "gDfe..."
    #
